name: Run shell script
on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: List Repository Files
        run: ls -ltra

      - name: Run She'll script
        run: ./shell-script.sh